name: Deployment Pipeline

env:
  DEPLOY_CONDITION: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: ${{ env.DEPLOY_CONDITION == 'true' }}
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps
      - name: Check style
        run: |
          npm run eslint
      - name: Build
        run: |
          npm run build
      - name: Test
        run: |
          npm run test
      - name: E2E Test
        run: |
          npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Deploy
        if: ${{ env.DEPLOY_CONDITION == 'true' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  tag_release:
    if: ${{ github.env.DEPLOY_CONDITION == 'true' }}
    needs:
      - simple_deployment_pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch
